version: '3.8'

services:
  vue-app:
    build:
      context: ./frontend  # Set the context to the frontend directory
      dockerfile: Dockerfile  # Point to the Dockerfile in the frontend directory
      args: 
        STUDENT_NAME: "Leonardo Tyoes Huibu"
        STUDENT_NIM: "00000065503"
    container_name: vue_app_container
    ports:
      - "80:80"  # Expose port 80 to the host
    networks:
      - app_network
    environment:
      - HOST=0.0.0.0
      - PORT=80 # Port for Nginx to serve the built Vue app

  backend:
    build:
      context: ./backend  # Set the context to the backend directory
      dockerfile: Dockerfile  # Ensure this points to the correct Dockerfile for the backend
      args: 
        STUDENT_NAME: "Leonardo Tyoes Huibu"
        STUDENT_NIM: "00000065503"
    container_name: backend_container
    expose:
      - "3000"  # Expose the backend port internally
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

