version: '3.8'

services:
  vue-app:
    build:
      context: ./frontend  # Set the context to the frontend directory
      dockerfile: Dockerfile  # Point to the Dockerfile in the frontend directory
      args: 
        STUDENT_NAME: "Leonardo Tyoes Huibu"
        STUDENT_NIM: "00000065503"
    container_name: vue_app_container
    # No need to expose 5173 as we are using Nginx to serve
    # environment:
    #   - HOST=0.0.0.0
    #   - PORT=5173 # This is no longer necessary
    networks:
      - app_network

  backend:
    build:
      context: ./backend  # Set the context to the backend directory
      dockerfile: Dockerfile  # Ensure this points to the correct Dockerfile for the backend
      args: 
        STUDENT_NAME: "Leonardo Tyoes Huibu"
        STUDENT_NIM: "00000065503"
    container_name: backend_container
    expose:
      - "3000"  # Expose the backend port internally (if needed for the frontend)
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx  # Set the context to where your Nginx Dockerfile is (if you have a Dockerfile for custom Nginx image)
      dockerfile: Dockerfile  # You may have a custom Dockerfile for Nginx if needed
    container_name: nginx_container
    ports:
      - "80:80"  # Expose port 80 to the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Map your custom nginx configuration
    depends_on:
      - vue-app
      - backend  # Ensure the backend is also available before starting Nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

